use std::path::Path;
use std::{env, fs};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")?;
    let products_dir = Path::new(&manifest_dir).join("src/products");
    let out_dir = env::var("OUT_DIR")?;
    let dest = Path::new(&out_dir).join("product_includes.rs");

    // Rerun when any file in products/ changes (add/remove/modify)
    println!("cargo:rerun-if-changed=src/products");

    let mut entries: Vec<String> = fs::read_dir(&products_dir)?
        .filter_map(|e| e.ok())
        .filter_map(|e| {
            let path = e.path();
            if path.extension().and_then(|x| x.to_str()) == Some("json") {
                let name = path.file_name()?.to_str()?.to_string();
                Some(name)
            } else {
                None
            }
        })
        .collect();

    // Sort for deterministic builds
    entries.sort();

    let includes: Vec<String> = entries
        .iter()
        .map(|name| {
            let abs = products_dir.join(name);
            format!("    include_str!({:?}),", abs.to_string_lossy())
        })
        .collect();

    let generated = format!(
        "// Auto-generated by build.rs — do not edit\n&[\n{}\n]",
        includes.join("\n")
    );

    fs::write(&dest, generated)?;
    Ok(())
}
