[mqtt]
endpoint = d08715432na143627x533-ats.iot.us-east-1.amazonaws.com
port = 8883
ca = ./ssl/AmazonRootCA1.pem
cert = ./ssl/client-certificate.pem.crt
key = ./ssl/client-private.pem.key

[client]
session_timeout_minutes = 10
command_reply_timeout_seconds = 20
