[package]
name = "workspace-hack"
version = "0.1.0"
edition = "2024"
publish = false

# workspace-hack is managed by cargo-hakari.
# See https://docs.rs/cargo-hakari/latest/cargo_hakari/about/index.html

### BEGIN HAKARI SECTION
[dependencies]
axum = { version = "0.8", features = ["http2", "macros", "multipart", "ws"] }
base64 = { version = "0.22" }
byteorder = { version = "1" }
chrono = { version = "0.4", features = ["serde"] }
cipher = { version = "0.4", default-features = false, features = ["block-padding"] }
clap = { version = "4", features = ["cargo", "derive", "env"] }
clap_builder = { version = "4", default-features = false, features = ["cargo", "color", "env", "help", "std", "suggestions", "usage"] }
const-oid = { version = "0.9", default-features = false, features = ["db", "std"] }
crossbeam-utils = { version = "0.8" }
crypto-common = { version = "0.1", default-features = false, features = ["std"] }
digest = { version = "0.10", features = ["mac", "oid", "std"] }
either = { version = "1", features = ["serde", "use_std"] }
fastrand = { version = "2" }
flate2 = { version = "1", features = ["zlib-rs"] }
futures-channel = { version = "0.3", features = ["sink"] }
futures-executor = { version = "0.3" }
futures-io = { version = "0.3" }
futures-sink = { version = "0.3" }
futures-util = { version = "0.3", default-features = false, features = ["async-await-macro", "channel", "io", "sink"] }
getrandom-468e82937335b1c9 = { package = "getrandom", version = "0.3", default-features = false, features = ["std", "wasm_js"] }
getrandom-6f8ce4dd05d13bba = { package = "getrandom", version = "0.2", default-features = false, features = ["std"] }
hmac = { version = "0.12", default-features = false, features = ["reset"] }
hyper = { version = "1", features = ["http1", "http2", "server"] }
hyper-util = { version = "0.1", features = ["http1", "http2", "server", "service", "tokio"] }
indexmap = { version = "2", features = ["serde"] }
inout = { version = "0.1", default-features = false, features = ["block-padding"] }
lazy_static = { version = "1", default-features = false, features = ["spin_no_std"] }
log = { version = "0.4", default-features = false, features = ["std"] }
memchr = { version = "2" }
mio = { version = "1", features = ["net", "os-ext"] }
num-traits = { version = "0.2", default-features = false, features = ["i128", "libm", "std"] }
once_cell = { version = "1" }
parking_lot = { version = "0.12", features = ["send_guard"] }
rand = { version = "0.8" }
regex-automata = { version = "0.4", default-features = false, features = ["dfa-build", "dfa-onepass", "hybrid", "meta", "nfa-backtrack", "perf-inline", "perf-literal", "std", "unicode"] }
regex-syntax = { version = "0.8" }
rumqttc = { version = "0.24" }
scopeguard = { version = "1" }
serde = { version = "1", features = ["alloc", "derive", "rc"] }
serde_core = { version = "1", features = ["alloc", "rc"] }
serde_json = { version = "1", features = ["raw_value"] }
sha1 = { version = "0.10", features = ["oid"] }
sha2 = { version = "0.10", features = ["oid"] }
simd-adler32 = { version = "0.3", default-features = false, features = ["std"] }
smallvec = { version = "1", default-features = false, features = ["const_new", "serde"] }
sqlx = { version = "0.8", default-features = false, features = ["chrono", "json", "macros", "postgres", "runtime-tokio-rustls", "sqlite", "uuid"] }
sqlx-core = { version = "0.8", features = ["_rt-tokio", "_tls-rustls-ring-webpki", "any", "chrono", "json", "migrate", "offline", "uuid"] }
sqlx-postgres = { version = "0.8", default-features = false, features = ["chrono", "json", "migrate", "offline", "uuid"] }
sqlx-sqlite = { version = "0.8", default-features = false, features = ["bundled", "chrono", "json", "migrate", "offline", "uuid"] }
sync_wrapper = { version = "1", default-features = false, features = ["futures"] }
time = { version = "0.3", features = ["formatting", "macros", "parsing"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["fs", "sync"] }
tracing-core = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "time"] }
uuid = { version = "1", features = ["serde", "v4"] }
zeroize = { version = "1", features = ["zeroize_derive"] }

[build-dependencies]
axum = { version = "0.8", features = ["http2", "macros", "multipart", "ws"] }
base64 = { version = "0.22" }
byteorder = { version = "1" }
cc = { version = "1", default-features = false, features = ["parallel"] }
chrono = { version = "0.4", features = ["serde"] }
cipher = { version = "0.4", default-features = false, features = ["block-padding"] }
clap = { version = "4", features = ["cargo", "derive", "env"] }
clap_builder = { version = "4", default-features = false, features = ["cargo", "color", "env", "help", "std", "suggestions", "usage"] }
const-oid = { version = "0.9", default-features = false, features = ["db", "std"] }
crossbeam-utils = { version = "0.8" }
crypto-common = { version = "0.1", default-features = false, features = ["std"] }
digest = { version = "0.10", features = ["mac", "oid", "std"] }
either = { version = "1", features = ["serde", "use_std"] }
fastrand = { version = "2" }
flate2 = { version = "1", features = ["zlib-rs"] }
futures-channel = { version = "0.3", features = ["sink"] }
futures-executor = { version = "0.3" }
futures-io = { version = "0.3" }
futures-sink = { version = "0.3" }
futures-util = { version = "0.3", default-features = false, features = ["async-await-macro", "channel", "io", "sink"] }
getrandom-468e82937335b1c9 = { package = "getrandom", version = "0.3", default-features = false, features = ["std", "wasm_js"] }
getrandom-6f8ce4dd05d13bba = { package = "getrandom", version = "0.2", default-features = false, features = ["std"] }
hmac = { version = "0.12", default-features = false, features = ["reset"] }
hyper = { version = "1", features = ["http1", "http2", "server"] }
hyper-util = { version = "0.1", features = ["http1", "http2", "server", "service", "tokio"] }
indexmap = { version = "2", features = ["serde"] }
inout = { version = "0.1", default-features = false, features = ["block-padding"] }
lazy_static = { version = "1", default-features = false, features = ["spin_no_std"] }
log = { version = "0.4", default-features = false, features = ["std"] }
memchr = { version = "2" }
mio = { version = "1", features = ["net", "os-ext"] }
num-traits = { version = "0.2", default-features = false, features = ["i128", "libm", "std"] }
once_cell = { version = "1" }
parking_lot = { version = "0.12", features = ["send_guard"] }
proc-macro2 = { version = "1" }
quote = { version = "1" }
rand = { version = "0.8" }
regex-automata = { version = "0.4", default-features = false, features = ["dfa-build", "dfa-onepass", "hybrid", "meta", "nfa-backtrack", "perf-inline", "perf-literal", "std", "unicode"] }
regex-syntax = { version = "0.8" }
rumqttc = { version = "0.24" }
scopeguard = { version = "1" }
serde = { version = "1", features = ["alloc", "derive", "rc"] }
serde_core = { version = "1", features = ["alloc", "rc"] }
serde_json = { version = "1", features = ["raw_value"] }
sha1 = { version = "0.10", features = ["oid"] }
sha2 = { version = "0.10", features = ["oid"] }
simd-adler32 = { version = "0.3", default-features = false, features = ["std"] }
smallvec = { version = "1", default-features = false, features = ["const_new", "serde"] }
sqlx = { version = "0.8", default-features = false, features = ["chrono", "json", "macros", "postgres", "runtime-tokio-rustls", "sqlite", "uuid"] }
sqlx-core = { version = "0.8", features = ["_rt-tokio", "_tls-rustls-ring-webpki", "any", "chrono", "json", "migrate", "offline", "uuid"] }
sqlx-macros = { version = "0.8", features = ["_rt-tokio", "_tls-rustls-ring-webpki", "chrono", "derive", "json", "macros", "postgres", "sqlite", "uuid"] }
sqlx-macros-core = { version = "0.8", features = ["_rt-tokio", "_tls-rustls-ring-webpki", "chrono", "derive", "json", "macros", "postgres", "sqlite", "uuid"] }
sqlx-postgres = { version = "0.8", default-features = false, features = ["chrono", "json", "migrate", "offline", "uuid"] }
sqlx-sqlite = { version = "0.8", default-features = false, features = ["bundled", "chrono", "json", "migrate", "offline", "uuid"] }
syn = { version = "2", features = ["extra-traits", "fold", "full", "visit", "visit-mut"] }
sync_wrapper = { version = "1", default-features = false, features = ["futures"] }
time = { version = "0.3", features = ["formatting", "macros", "parsing"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["fs", "sync"] }
tracing-core = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "time"] }
uuid = { version = "1", features = ["serde", "v4"] }
zeroize = { version = "1", features = ["zeroize_derive"] }

### END HAKARI SECTION
