[package]
name = "voltage-rtdb-shm"
version.workspace = true
edition = "2024"
license.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
voltage-model = { path = "../voltage-model" }
voltage-routing = { path = "../voltage-routing" }
bytemuck = { workspace = true }
rustc-hash = { workspace = true }
anyhow = { workspace = true }
sqlx = { workspace = true }
memmap2 = "0.9"
arc-swap = "1.7"
tokio = { workspace = true }
tracing = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[dev-dependencies]
tempfile = "3.10"

[lints]
workspace = true
