#!/bin/sh
set -eu

if [ "${1:-}" = "remove" ] || [ "${1:-}" = "upgrade" ] || [ "${1:-}" = "deconfigure" ]; then
    systemctl stop awsiot-mqtt-terminal.service >/dev/null 2>&1 || true
    systemctl disable awsiot-mqtt-terminal.service >/dev/null 2>&1 || true
fi
