//! Channel management CRUD handlers
//!
//! This module contains handlers for:
//! - Creating new channels with hot startup
//! - Updating channel configurations with hot reload
//! - Enabling/disabling channels
//! - Deleting channels
//! - Reloading all channels from database

mod helpers;
mod lifecycle;
mod migration;
mod reload;

// Re-export everything (including utoipa __path_* structs generated by the macro)
pub use lifecycle::*;
pub use reload::*;

use crate::api::routes::AppState;
use crate::core::config::ChannelCore;
use crate::dto::{AppError, ParameterChangeType, SuccessResponse};
use axum::{
    extract::{Path, State},
    response::Json,
};
use helpers::*;
#[allow(unused_imports)] // Used in utoipa examples
use serde_json::json;
use std::sync::Arc;
use voltage_rtdb::Rtdb;

/// Create a new channel with hot startup
///
/// @route POST /api/channels
/// @input State(state): AppState - Application state with manager and SQLite
/// @input Json(req): ChannelCreateRequest - Channel configuration
/// @output `Json<ApiResponse<ChannelCrudResult>>` - Creation result
/// @status 200 - Channel created and started successfully
/// @status 400 - Invalid request or validation error
/// @status 500 - Database or runtime error
/// @side-effects Creates channel in SQLite and starts it in runtime
#[utoipa::path(
    post,
    path = "/api/channels",
    request_body(
        content = crate::dto::ChannelCreateRequest,
        description = "Channel creation request with protocol-specific parameters",
        examples(
            ("Modbus TCP - Basic" = (
                summary = "Modbus TCP channel (basic parameters)",
                value = json!({
                    "name": "PV Inverter 01",
                    "description": "Primary PV inverter communication",
                    "protocol": "modbus_tcp",
                    "enabled": true,
                    "parameters": {
                        "host": "192.168.1.100",
                        "port": 502
                    }
                })
            )),
            ("Modbus TCP - Full" = (
                summary = "Modbus TCP channel (all parameters)",
                value = json!({
                    "name": "PV Inverter 02",
                    "description": "Secondary PV inverter with custom settings",
                    "protocol": "modbus_tcp",
                    "enabled": true,
                    "parameters": {
                        "host": "192.168.1.101",
                        "port": 502,
                        "connect_timeout_ms": 5000,
                        "read_timeout_ms": 3000,
                        "polling_interval_ms": 1000,
                        "max_batch_size": 64
                    }
                })
            )),
            ("Modbus RTU - Full" = (
                summary = "Modbus RTU channel (complete configuration)",
                description = "Battery Management System with all RTU parameters",
                value = json!({
                    "name": "Battery Pack RTU",
                    "description": "Battery management system with full parameters",
                    "protocol": "modbus_rtu",
                    "enabled": true,
                    "parameters": {
                        "device": "/dev/ttyUSB0",
                        "baud_rate": 9600,
                        "connect_timeout_ms": 5000,
                        "io_timeout_ms": 3000,
                        "max_batch_size": 64
                    }
                })
            )),
            ("DI/DO GPIO (sysfs)" = (
                summary = "DI/DO GPIO - sysfs driver (legacy)",
                description = "Digital I/O using legacy sysfs interface (/sys/class/gpio). Use global GPIO numbers.",
                value = json!({
                    "name": "ECU1170 GPIO",
                    "description": "Digital I/O for industrial controller",
                    "protocol": "di_do",
                    "enabled": true,
                    "parameters": {
                        "driver": "sysfs",
                        "gpio_base_path": "/sys/class/gpio",
                        "di_poll_interval_ms": 200
                    }
                })
            )),
            ("DI/DO GPIO (gpiod)" = (
                summary = "DI/DO GPIO - gpiod driver (recommended)",
                description = "Digital I/O using modern chardev interface (/dev/gpiochipN). Use chip name + pin offset.",
                value = json!({
                    "name": "ECU1170 GPIO",
                    "description": "Digital I/O for industrial controller",
                    "protocol": "di_do",
                    "enabled": true,
                    "parameters": {
                        "driver": "gpiod",
                        "gpio_chip": "gpiochip6",
                        "poll_interval_ms": 200
                    }
                })
            )),
            ("CAN Bus" = (
                summary = "CAN Bus channel (Discover LYNK Serial CAN)",
                description = "Standard CAN 2.0B channel via SocketCAN. `device` is the host SocketCAN interface name (e.g. can0, vcan0). All timeout/interval fields are optional and fall back to the shown defaults.",
                value = json!({
                    "name": "lynk_serial_can",
                    "description": "Discover LYNK Serial CAN 协议示例",
                    "protocol": "can",
                    "enabled": true,
                    "parameters": {
                        "device": "can0",
                        "bitrate": 250000,
                        "connect_timeout_ms": 3000,
                        "read_timeout_ms": 3000,
                        "retry_interval_ms": 2000,
                        "rx_poll_interval_ms": 50,
                        "data_read_interval_ms": 1000
                    }
                })
            )),
            ("Virtual - Test" = (
                summary = "Virtual test channel",
                value = json!({
                    "name": "Test Channel",
                    "description": "Virtual channel for testing",
                    "protocol": "virtual",
                    "enabled": true,
                    "parameters": {
                        "update_interval_ms": 1000
                    }
                })
            ))
        )
    ),
    responses(
        (status = 200, description = "Channel created successfully", body = crate::dto::ChannelCrudResult),
        (status = 400, description = "Invalid request (validation failed)"),
        (status = 409, description = "Conflict (name or ID already exists)"),
        (status = 500, description = "Internal server error")
    ),
    tag = "comsrv"
)]
pub async fn create_channel_handler<R: Rtdb>(
    State(state): State<AppState<R>>,
    Json(req): Json<crate::dto::ChannelCreateRequest>,
) -> Result<Json<SuccessResponse<crate::dto::ChannelCrudResult>>, AppError> {
    use crate::core::config::ChannelConfig;

    // 1. Check if channel name already exists (enforced uniqueness)
    let existing_name: Option<i64> =
        sqlx::query_scalar("SELECT channel_id FROM channels WHERE name = ?")
            .bind(&req.name)
            .fetch_optional(&state.sqlite_pool)
            .await
            .map_err(|e| AppError::internal_error(format!("Database error: {}", e)))?;

    if let Some(existing_id) = existing_name {
        return Err(AppError::conflict(format!(
            "Channel name '{}' already exists (ID: {})",
            req.name, existing_id
        )));
    }

    // 2. Determine channel ID (auto-assign or use provided)
    let channel_id = if let Some(id) = req.channel_id {
        check_channel_id_available(id, &state.sqlite_pool, &state.channel_manager).await?;
        tracing::debug!("Manual ID: {}", id);
        id
    } else {
        // Auto-assign ID: find MAX + 1
        let max_id: Option<i64> = sqlx::query_scalar("SELECT MAX(channel_id) FROM channels")
            .fetch_optional(&state.sqlite_pool)
            .await
            .map_err(|e| AppError::internal_error(format!("Database error: {}", e)))?;

        let max_val = max_id.unwrap_or(0);
        let next_id_i64 = max_val.checked_add(1).ok_or_else(|| {
            AppError::internal_error("Channel ID overflow: max_id + 1 overflowed")
        })?;
        let next_id = u32::try_from(next_id_i64).map_err(|_| {
            AppError::internal_error(format!("Channel ID {} exceeds u32 max", next_id_i64))
        })?;
        tracing::debug!("Auto ID: {}", next_id);
        next_id
    };

    tracing::debug!("Creating Ch{}: {} ({})", channel_id, req.name, req.protocol);

    let enabled = req.enabled.unwrap_or(true);

    // 3. Build channel config
    let channel_config = ChannelConfig {
        core: ChannelCore {
            id: channel_id,
            name: req.name.clone(),
            description: req.description.clone(),
            protocol: req.protocol.clone(),
            enabled,
        },
        parameters: req.parameters.clone(),
        logging: req.logging.clone().unwrap_or_default(),
    };

    // Determine runtime status based on enabled flag
    let runtime_status = if enabled {
        // enabled = true: Create runtime channel and connect in background (non-blocking)
        // Direct access without RwLock (lock-free)
        let manager = &state.channel_manager;
        match manager.create_channel(Arc::new(channel_config)).await {
            Ok(entry) => {
                // Spawn background connection to avoid failing API on initial connect error
                // Fire-and-forget: connection is best-effort, errors are logged
                let channel_id_for_log = channel_id;
                tokio::spawn(async move {
                    if let Err(e) = entry.connect().await {
                        tracing::warn!("Ch{} connect: {}", channel_id_for_log, e);
                    } else {
                        tracing::debug!("Ch{} connected", channel_id_for_log);
                    }
                });
                "connecting".to_string()
            },
            Err(e) => {
                tracing::warn!("Create Ch{} runtime: {}", channel_id, e);
                "not_started".to_string()
            },
        }
    } else {
        // enabled = false: Skip runtime creation, just write to database
        tracing::debug!("Ch{} created (disabled)", channel_id);
        "stopped".to_string()
    };

    // 3. Runtime successful, now write to database
    // Build config JSON in structured format
    let logging = req.logging.clone().unwrap_or_default();
    let config_json =
        build_channel_config_json(req.description.as_ref(), &req.parameters, &logging)
            .map_err(|e| AppError::internal_error(format!("Failed to build config JSON: {}", e)))?;

    if let Err(e) = sqlx::query(
        "INSERT INTO channels (channel_id, name, protocol, enabled, config) VALUES (?, ?, ?, ?, ?)",
    )
    .bind(channel_id as i64)
    .bind(&req.name)
    .bind(&req.protocol)
    .bind(enabled)
    .bind(&config_json)
    .execute(&state.sqlite_pool)
    .await
    {
        tracing::error!("Insert Ch{}: {}", channel_id, e);
        // Database write failed, remove the runtime channel
        // Direct access without RwLock (lock-free)
        let manager = &state.channel_manager;
        let _ = manager.remove_channel(channel_id).await;
        return Err(AppError::internal_error(format!("Database error: {}", e)));
    }

    let result = crate::dto::ChannelCrudResult {
        core: ChannelCore {
            id: channel_id,
            name: req.name,
            description: req.description,
            protocol: req.protocol,
            enabled,
        },
        runtime_status,
        message: Some(if enabled {
            "Channel created and started successfully".to_string()
        } else {
            "Channel created in disabled state".to_string()
        }),
    };

    Ok(Json(SuccessResponse::new(result)))
}

/// Update an existing channel configuration
///
/// Updates channel configuration (name, protocol, parameters) without changing enabled state.
/// If the channel is running, it will be hot-reloaded with the new configuration.
/// Use PUT /api/channels/{id}/enabled to change the enabled state.
///
/// ## Channel ID Migration
/// If `channel_id` is provided in the request body and differs from the path ID,
/// the channel will be migrated to the new ID. This includes:
/// - Updating all related tables (points, mappings, routing)
/// - Restarting the channel with the new ID
///
/// @route PUT /api/channels/{id}
/// @side-effects Updates SQLite and hot-reloads if running; migrates all data if channel_id changed
#[utoipa::path(
    put,
    path = "/api/channels/{id}",
    params(
        ("id" = u32, Path, description = "Current channel identifier (or ID to migrate from)")
    ),
    request_body(
        content = crate::dto::ChannelConfigUpdateRequest,
        description = "Channel update request. Include channel_id to migrate to a new ID.",
        examples(
            ("Update name only" = (
                summary = "Update channel name",
                value = json!({
                    "name": "Updated Channel Name"
                })
            )),
            ("Migrate channel ID" = (
                summary = "Change channel ID from 13 to 6",
                description = "Migrates all related data (points, mappings, routing) to the new ID",
                value = json!({
                    "channel_id": 6,
                    "name": "1DL2-2 (2)"
                })
            )),
            ("Update parameters" = (
                summary = "Update connection parameters",
                value = json!({
                    "parameters": {
                        "host": "192.168.1.101",
                        "timeout_ms": 10000
                    }
                })
            ))
        )
    ),
    responses(
        (status = 200, description = "Channel updated successfully", body = crate::dto::ChannelCrudResult),
        (status = 404, description = "Channel not found"),
        (status = 409, description = "Conflict - new channel_id already exists"),
        (status = 500, description = "Internal server error")
    ),
    tag = "comsrv"
)]
pub async fn update_channel_handler<R: Rtdb + 'static>(
    Path(id): Path<u32>,
    State(state): State<AppState<R>>,
    Json(req): Json<crate::dto::ChannelConfigUpdateRequest>,
) -> Result<Json<SuccessResponse<crate::dto::ChannelCrudResult>>, AppError> {
    // Check if channel ID migration is requested
    if let Some(new_id) = req.channel_id
        && new_id != id
    {
        tracing::info!("Ch{} -> Ch{} ID migration requested", id, new_id);
        return migration::change_channel_id(id, new_id, req, &state).await;
    }

    tracing::debug!("Ch{} updating", id);

    // 1. Check if channel is currently running
    let is_running = {
        // Direct access without RwLock (lock-free)
        let manager = &state.channel_manager;
        manager.get_channel(id).is_some()
    };

    // 2. Load current configuration from database
    let (current_name, current_protocol, enabled, current_config_str) =
        load_channel_from_db(&state.sqlite_pool, id).await?;

    // 3. Begin database transaction
    let mut tx = state
        .sqlite_pool
        .begin()
        .await
        .map_err(|e| AppError::internal_error(format!("Database operation failed: {}", e)))?;

    // 4. Apply configuration updates to database
    // Use unwrap_or_else for lazy evaluation - avoids clone when req.* is Some
    let name = req.name.clone().unwrap_or_else(|| current_name.clone());
    let protocol = req
        .protocol
        .clone()
        .unwrap_or_else(|| current_protocol.clone());

    // Check if new name conflicts with existing channels (excluding current channel)
    if req.name.is_some() {
        let existing_name: Option<i64> = sqlx::query_scalar(
            "SELECT channel_id FROM channels WHERE name = ? AND channel_id != ?",
        )
        .bind(&name)
        .bind(id as i64)
        .fetch_optional(&mut *tx)
        .await
        .map_err(|e| AppError::internal_error(format!("Database operation failed: {}", e)))?;

        if let Some(existing_id) = existing_name {
            return Err(AppError::conflict(format!(
                "Channel name '{}' already exists (ID: {})",
                name, existing_id
            )));
        }

        sqlx::query("UPDATE channels SET name = ? WHERE channel_id = ?")
            .bind(&name)
            .bind(id as i64)
            .execute(&mut *tx)
            .await
            .map_err(|e| AppError::internal_error(format!("Database operation failed: {}", e)))?;
    }

    if req.protocol.is_some() {
        sqlx::query("UPDATE channels SET protocol = ? WHERE channel_id = ?")
            .bind(&protocol)
            .bind(id as i64)
            .execute(&mut *tx)
            .await
            .map_err(|e| AppError::internal_error(format!("Database operation failed: {}", e)))?;
    }

    // Extract current configuration for restoration and apply requested updates
    // Move current_config_str since it's only used here
    let (previous_description, previous_parameters, previous_logging) =
        parse_channel_config(id, current_config_str)?;

    // Clone previous values since they're needed later for change detection
    let mut description = previous_description.clone();
    let mut parameters = previous_parameters.clone();
    let mut logging = previous_logging.clone();

    if let Some(new_description) = &req.description {
        description = Some(new_description.clone());
    }

    if let Some(params) = &req.parameters {
        for (key, value) in params {
            parameters.insert(key.clone(), value.clone());
        }
    }

    if let Some(new_logging) = &req.logging {
        logging = new_logging.clone();
    }

    if req.description.is_some() || req.parameters.is_some() || req.logging.is_some() {
        let config_json = build_channel_config_json(description.as_ref(), &parameters, &logging)
            .map_err(|e| {
                tracing::error!("Serialize Ch{}: {}", id, e);
                AppError::internal_error(format!("Failed to build config JSON: {}", e))
            })?;

        sqlx::query("UPDATE channels SET config = ? WHERE channel_id = ?")
            .bind(&config_json)
            .bind(id as i64)
            .execute(&mut *tx)
            .await
            .map_err(|e| AppError::internal_error(format!("Database operation failed: {}", e)))?;
    }

    // 5. Analyze parameter changes to determine if hot reload is needed
    let name_changed = req.name.is_some() && req.name.as_ref() != Some(&current_name);
    let description_changed = req.description.is_some() && req.description != previous_description;
    let protocol_changed =
        req.protocol.is_some() && req.protocol.as_ref() != Some(&current_protocol);

    let change_type = if is_running {
        analyze_parameter_changes(
            &previous_parameters,
            &parameters,
            name_changed,
            description_changed,
            protocol_changed,
        )
    } else {
        ParameterChangeType::MetadataOnly // Not running, no need to reload
    };

    tracing::debug!("Ch{} change: {:?}", id, change_type);

    // 6. Hot reload if channel is running and changes require it
    let runtime_status = if is_running {
        use ParameterChangeType::*;

        match change_type {
            MetadataOnly => {
                // Only name or description changed, no hot reload needed
                tracing::debug!("Ch{} metadata only", id);
                tx.commit().await.map_err(|e| {
                    AppError::internal_error(format!("Database operation failed: {}", e))
                })?;

                // Apply logging config change at runtime (no hot reload needed)
                if req.logging.is_some() {
                    let level = logging.level.as_deref().unwrap_or(if logging.enabled {
                        "info"
                    } else {
                        "error" // disabled = minimal logging
                    });
                    if let Some(entry) = state.channel_manager.get_channel(id) {
                        if let Err(e) = entry.set_log_level(level).await {
                            tracing::warn!("Ch{} set log level failed: {}", id, e);
                        } else {
                            tracing::info!("Ch{} log level set to {}", id, level);
                        }
                    }
                }

                "running".to_string()
            },
            NonCritical | Critical => {
                tracing::debug!("Ch{} {:?} change, hot reload", id, change_type);

                tx.commit().await.map_err(|e| {
                    AppError::internal_error(format!("Database operation failed: {}", e))
                })?;

                let new_config = crate::core::config::ChannelConfig {
                    core: ChannelCore {
                        id,
                        name: name.clone(),
                        description: description.clone(),
                        protocol: protocol.clone(),
                        enabled,
                    },
                    parameters,
                    logging,
                };

                let state_clone = state.clone();
                tokio::spawn(async move {
                    if let Err(e) = perform_hot_reload(id, &state_clone, new_config).await {
                        tracing::error!("Ch{} hot reload: {}", id, e);
                    }
                });

                "updated".to_string()
            },
        }
    } else {
        // Channel not running, just commit DB changes
        tx.commit()
            .await
            .map_err(|e| AppError::internal_error(format!("Database operation failed: {}", e)))?;
        tracing::debug!("Ch{} updated (stopped)", id);
        "stopped".to_string()
    };

    // Update channel name in Redis hash if name changed
    // This ensures Redis cache is consistent even for MetadataOnly changes
    if name_changed {
        let keyspace = voltage_model::KeySpaceConfig::production_cached();
        let channels_key = keyspace.channels_hash_key();
        match state
            .rtdb
            .hash_set(
                &channels_key,
                &id.to_string(),
                bytes::Bytes::from(name.clone()),
            )
            .await
        {
            Err(e) => {
                // Redis is cache layer - log warning but don't fail the request
                tracing::warn!(
                    "Ch{} failed to update name in Redis hash ({}): {}",
                    id,
                    channels_key,
                    e
                );
            },
            _ => {
                tracing::debug!("Ch{} name updated in Redis hash: {}", id, channels_key);
            },
        }
    }

    // Use the final description after applying updates (or keep previous if not provided)
    let result = crate::dto::ChannelCrudResult {
        core: ChannelCore {
            id,
            name,
            description, // propagate actual description
            protocol,
            enabled,
        },
        runtime_status,
        message: Some("Channel configuration updated successfully".to_string()),
    };

    Ok(Json(SuccessResponse::new(result)))
}
